# _config.yml

# Server Config

safe: true

source: ./web
destination: ./beta
safe: true

timezone: Europe/London
encoding: "utf-8"

future: false

## Collections

collections:
  awards:
    output: true
    permalink: /categories/:path/
  partners:
    output: true
    permalink: /partners/:path/
  judges:
    output: true
    permalink: /judges/:path/

## Conversion

markdown: kramdown
highlighter: pygments
lsi: false
excerpt_separator: "\n\n"

## Backwards-compatibility

relative_permalinks: false

# Site Config

name: Coventry Telegrphy Business Awards 2015

url: //www.ctbusinessawards.co.uk/beta
static: //www.ctbusinessawards.co.uk/beta/static
media: //www.ctbusinessawards.co.uk/beta/media
api: //www.ctbusinessawards.co.uk/api

## Analytics

google_analytics_id:

## Meta

meta:
  author: author
  description: "The Coventry Telegraph is celebrating the resilience and fortitude of business and industries in Birmingham, West Midlands. Nominate your business for a award."
  keywords:
